TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  format: 'lmdb'
  dataroot: data/flickr30k
  features_h5path1: data/flickr30k/features/flickr30k_X101.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: data/flickr30k/annotations/train_ann.jsonl
  val_annotations_jsonpath: data/flickr30k/annotations/valid_ann.jsonl
  max_seq_length: 80
  max_region_num: 100
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 10
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  format: 'lmdb'
  dataroot: data/nlvr2/annotations
  features_h5path1: data/nlvr2/features/nlvr2_X101.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 100
  batch_size: 64
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00001
  num_epoch: 20
TASK15:
  name: GQA
  type: VL-classifier-GQA
  num_labels: 1842
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  format: 'lmdb'
  dataroot: data/gqa/annotations
  features_h5path1: data/gqa/features/vg-gqa_X101.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 40
  max_region_num: 100
  batch_size: 256
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 5
TASK19:
  name: XVNLI
  type: VL-tri-classifier
  num_labels: 3
  loss: BCEWithLogitLoss
  process: normal
  task_id: 19
  format: 'lmdb'
  dataroot: data/XVNLI/annotations/en
  features_h5path1: data/flickr30k/features/flickr30k_X101.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 100
  batch_size: 128
  eval_batch_size: 1024
  train_split: train
  val_split: dev
  lr: 0.00002
  num_epoch: 10