TASK8:
  name: RetrievalxFlickrCO
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  format: 'lmdb'
  dataroot: data/flickr30k
  features_h5path1: data/xFlickrCO/features/xflickrco-test_boxes36.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: data/xFlickrCO/annotations/en/test.jsonl
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  format: 'lmdb'
  dataroot: data/nlvr2/annotations
  features_h5path1: data/nlvr2/features/nlvr2_boxes36.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK15:
  name: GQA
  type: VL-classifier-GQA
  num_labels: 1842
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  format: 'lmdb'
  dataroot: data/gqa/annotations
  features_h5path1: data/gqa/features/vg-gqa_boxes36.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 40
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK19:
  name: XVNLI
  type: VL-tri-classifier
  num_labels: 3
  loss: BCEWithLogitLoss
  process: normal
  task_id: 19
  format: 'lmdb'
  dataroot: data/XVNLI/annotations/en
  features_h5path1: data/flickr30k/features/flickr30k_boxes36.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: data/XVNLI/annotations/en/test.jsonl
  max_seq_length: 80
  max_region_num: 36
  batch_size: 1024
  val_split: test
TASK20:
  name: RetrievalWIT
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 20
  format: 'lmdb'
  dataroot: data/wit
  features_h5path1: data/wit/features/wit-en_test_boxes36.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: data/wit/annotations/test_en.jsonl
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test